name: 3dRegistration
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- jinja2=2.9.6=py36_0
- markupsafe=1.0=py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- tqdm=4.15.0=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0

